namespace: dellemc
name: os6
version: 1.0.6
readme: README.md
authors:
- Komal Patil <Komal_uttamrao_Patil@dell.com>
- Senthil Ganesan Ganesan <Senthil_Kumar_Ganesa@Dell.com>
description: Ansible Network Collection for Dell EMC OS6
license_file: LICENSE
tags: [dell, dellemc, os6, emc, networking]
dependencies:
  ansible.netcommon: '>=1.0.0'
repository: 'https://github.com/ansible-collections/dellemc.os6'
documentation: 'https://github.com/ansible-collections/dellemc.os6/tree/master/docs'
homepage: 'https://github.com/ansible-collections/dellemc.os6'
issues: 'https://github.com/ansible-collections/dellemc.os6/issues'
